config/routes.rb
Rails.application.routes.draw do
  resources :projects do
    post '/add_provider/:provider_id' => 'projects#add_provider', as: 'add_provider'
    resources :bookings
  end
  resources :needs, only: [:show]
  devise_for :organizations, controllers: { registrations: 'registrations' }
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :project

  def provider
    @provider_service = ProviderService.new
    @provider_service.provider_list.detect{|p| p['id'] = provider_id }
  end
end

app/models/need.rb
class Need < ApplicationRecord
  has_many :project_needs
  has_many :projects, through: :project_needs
end

app/models/organization.rb
class Organization < ApplicationRecord
  validates :name, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :projects
end

app/models/project.rb
class Project < ApplicationRecord
  belongs_to :organization
  has_many :project_needs, dependent: :destroy
  has_many :needs, through: :project_needs
  has_many :bookings, dependent: :destroy

  def all_needs=(names)
    self.needs = names.split(',').map do |name|
      Need.where(name: name.strip).first_or_create!
    end
  end

  def all_needs
    self.needs.map(&:name).join(', ')
  end

  def providers
    @provider ||= ProviderService.new(needs)
  end
end

app/models/project_need.rb
class ProjectNeed < ApplicationRecord
  belongs_to :project
  belongs_to :need
end

app/models/provider_service.rb
require 'open-uri'

class ProviderService
  attr_reader :needs

  def initialize(needs = [])
    @needs = needs.map(&:name)
  end

  def provider_list
    @provider_list = JSON.load(open("http://dinomic-env.iptbyyverm.us-east-1.elasticbeanstalk.com/getProviders"))
    if needs.empty?
      @provider_list['data']
    else
      @provider_list['data'].select do |d|
        (d['serviceProvided'] & @needs).any?
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(_)
    projects_path
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @bookings = @project.bookings.all
  end

  def new
    @project = Project.find(params[:project_id])
    @booking = @project.bookings.new(provider_id: params[:q])
  end

  def create
    @project = Project.find(params[:project_id])
    @booking = @project.bookings.new(booking_params)

    if @booking.save
      redirect_to project_bookings_path(@project) 
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:provider_id, :project_id, :starts_on, :ends_on)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: 'jumbotron'
  end
end

app/controllers/needs_controller.rb
class NeedsController < ApplicationController
  before_action :set_need

  def show; end

  private

  def set_need
    @need = Need.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_organization!

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_organization.projects.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = current_organization.projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_organization.projects.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_provider
    @project = Project.find(params[:project_id])
    @project.provider_ids << params[:provider_id].to_i
    @project.save
    redirect_to @project
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def project_params
    params.require(:project).permit(:organization_id, :title, :location, :all_needs, :description)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:organization).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:organization).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/needs_helper.rb
module NeedsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/_flashes.html.erb
<div class="container-fluid">
  <% unless notice.nil? %>
    <div class="alert alert-info mt-3"><%= notice %></div>
  <% end %>
  <% unless alert.nil? %>
    <div class="alert alert-danger mt-3"><%= alert %></div>
  <% end %>
</div>

app/views/application/_navbar.html.erb
<nav class="navbar navbar-expand-sm navbar-custom">
  <a class="navbar-brand" href="/">Hand to Heart</a>
  <button class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarCollapseContent"
          aria-controls="navbarCollapseContent"
          aria-expanded="false"
          aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarCollapseContent" >
    <ul class="navbar-nav mr-auto navbar-custom mx-auto">
      <div class="container">
        <div class="row">
          <div class="col-sm">
            <li class="nav-item">
              <a class="nav-link" href="/">About</a>
            </li>
          </div>
          <div class="col-sm">
            <li class="nav-item">
              <a class="nav-link" href="/projects">Projects</a>
            </li>
          </div>
          <div class="col-sm">
            <li class="nav-item">
              <a class="nav-link" href="#">Bookings</a>
            </li>
          </div>
        </div>
      </div>
    </ul>

    <ul class="navbar-nav ml-auto">

      <% if organization_signed_in? %>
        <li>
          <%= link_to current_organization.name, destroy_organization_session_path,
            method: :delete, class: "nav-link settings" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_organization_session_path,
            class: "nav-link" %>
        </li>
      <% end %>

    </ul>
  </div>
</nav>

app/views/bookings/index.html.erb
<% @bookings.each do |booking| %>
  <div class="card my-3">
    <div class="card-body">
      <h4 class="card-title">
        <%= booking.provider['name'] %>
      </h4>
      <div class="card-text">
        <%= booking.starts_on %> – <%= booking.starts_on %>
      </div>
    </div>
  </div>
<% end %>

app/views/bookings/new.html.erb
<%= form_with(model: [@project, @booking], local: true) do |form| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :provider_id, value: @booking.provider_id %>
  <div class="field">
    <%= form.date_field :starts_on %>
    <%= form.date_field :starts_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/index.html.erb
<div class="container about mx-auto">
  <p class="about">Hand to heart provides a platform that connects aid groups with help providers and contractors for long-term recontruction efforts after a natural disaster hits.</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dinomic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    
    <%= render 'flashes' %>

    <div class="container main">
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/jumbotron.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Dinomic</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'navbar' %>
    
    <%= render 'flashes' %>

    <%= yield %>
  </body>
</html>

app/views/needs/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @need.name %> Projects</h1>
<hr />

<div class="card-columns">
  <% @need.projects.each do |project| %>
    <div class="card">
      <img class="card-img-top" src="http://via.placeholder.com/350x150" alt="">
      <div class="card-body">
        <h4 class="card-title"><%= project.title %></h4>
        <p class="card-text"><%= project.location %></p>
      </div>
      <div class="card-footer">
        <%= link_to 'Show', project, class: "card-link" %>
        <%= link_to 'Edit', edit_project_path(project), class: "card-link" %>
        <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %>
      </div>
    </div>
  <% end %>
</div>

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <%= form.label :title, class: "form-label" %>
  <%= form.text_field :title, id: :project_title, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :location, class: "form-label" %>
  <%= form.text_field :location, id: :project_location, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :all_needs, class: "form-label" %>
  <%= form.text_field :all_needs, class: "form-control" %>
</div>

<div class="form-group">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
</div>

<div class="actions">
    <button type="submit" class="btn btn-primary ok-button">Save</button>
</div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<div class="container projects mx-auto">
  <p id="notice"><%= notice %></p>

  <h2 class="title">Projects</h2>

  <div class="card-columns">
      <% @projects.each do |project| %>
        <div class="card project-tile">
          <img class="card-img-top" src="http://via.placeholder.com/350x150" alt="">
          <div class="card-body">
            <h4 class="card-title"><%= project.title %></h4>
            <p class="card-text"><%= project.location %></p>
          </div>
          <div class="card-footer">
            <%= link_to 'Show', project, class: "card-link" %>
            <%= link_to 'Edit', edit_project_path(project), class: "card-link" %>
            <%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-link" %>
          </div>
        </div>
      <% end %>
  </div>
  <%= link_to 'New Project', new_project_path, class: "btn btn-primary ok-button", role:"button" %>
</div>

app/views/projects/new.html.erb
<div class="container projects mx-auto">
    <h2 class="title">New Project</h2>

    <%= render 'form', project: @project %>

    <%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<div class="card projec-detail">
  <img class="card-img-top" src="http://via.placeholder.com/700x300" alt="">
  <div class="card-body">
    <h4 class="card-title index"><%= @project.title %></h4>
    <p class="card-text"><%= @project.location %></p>
    <p class="card-text">
      <%= @project.description %>
    </p>
    <p class="card-text">
      <% @project.needs.each do |need| %>
        <%= link_to need.name, need, class: "badge badge-pill badge-primary" %>
      <% end %>
    </p>
    <p class="card-text">
      <%= link_to "Show bookings", project_bookings_path(@project), class: "btn btn-primary ok-button" %>
    </p>
  </div>
  <ul class="list-group">
    <% @project.provider_ids.each do |pid| %>
      <li class="list-group-item">
        <% @project.providers.provider_list.select{|p| p['id'] == pid}.each do |provider| %>
          <%= provider['name'] %>
          <% (provider['serviceProvided'] & @project.providers.needs).each do |need| %>
            <span class="badge badge-secondary badge-pill"><%= need %></span>
          <% end %>
          <%= link_to 'Book', new_project_booking_path(@project, q: pid), class: "btn btn-primary ok-button" %>
        <% end %>
      </li>
    <% end %>
  </ul>
  <div class="card-footer">
    <%= link_to 'Edit', edit_project_path(@project), class: "card-link" %>
    <%= link_to 'Back', projects_path, class: "card-link" %>
  </div>
</div>

<div class="my-5">
  <button class="btn btn-primary form-control"
          data-toggle="collapse" data-target="#providersList">
    Show Available Providers
  </button>

  <div id="providersList" class="collapse">
    <ul class="list-group list-group-flush">
      <% @project.providers.provider_list.each do |provider| %>
        <li class="list-group-item">
          <%= provider['name'] %>
          <% (provider['serviceProvided'] & @project.providers.needs).each do |need| %>
            <span class="badge badge-secondary badge-pill"><%= need %></span>
          <% end %>
          <button class="btn btn-sm btn-primary float-right" data-toggle="modal" data-target="#providerModal<%= provider['id'] %>">Show details</button>
        </li>

        <div id="providerModal<%= provider['id']%>" class="modal fade">
          <div class="modal-dialog">
            <div class="modal-content">
              <div class="modal-header">
                <h5 class="modal-title"><%= provider['name'] %></h5>
              </div>
              <div class="modal-body">
                <div class="col-xs-12">
                  <img class="img-fluid" src="<%= provider['logo'] %>" alt="" />
                </div>
                <p><%= provider['address'] %></p>
                <p><%= provider['phone'] %></p>
                <p><%= provider['location'] %></p>
                <p><%= link_to 'Homepage', provider['url'] %></p>
                <p>
                  <% provider['serviceProvided'].each do |service| %>
                    <span class="badge badge-secondary badge-pill"><%= service %></span>
                  <% end %>
                </p>
                <%= link_to 'Add to Project', project_add_provider_path(@project, provider['id']), method: :post, class:  "btn btn-primary form-control" %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>